onboarding = false
[theme]
name = "one-light"
auto_switch = false

[ui]
show_agent_labels_on_pane_borders = false
agent_panel_sort = "spaces"

[ui.toast]
delivery = "herdr"

[keys]
prefix="ctrl+s"

focus_pane_left = "ctrl+h"
focus_pane_down = "ctrl+j"
focus_pane_up = "ctrl+k"
focus_pane_right = "ctrl+l"

split_vertical = 'prefix+"'
split_horizontal = "prefix+%"

open_worktree = "prefix+shift+o"
remove_worktree = "prefix+shift+d"
close_workspace = "prefix+shift+k"

[[keys.command]]
key = "prefix+d"
type = "plugin_action"
command = "persiyanov.reviewr.toggle"

[ui.sound]
enabled = false
