onboarding = false
[theme]
name = "one-light"
auto_switch = false

[ui]
show_agent_labels_on_pane_borders = false
agent_panel_sort = "spaces"

[ui.toast]
delivery = "herdr"

[keys]
prefix="ctrl+s"

split_vertical = 'prefix+"'
split_horizontal = "prefix+%"

open_worktree = "prefix+shift+o"
remove_worktree = "prefix+shift+d"
close_workspace = "prefix+shift+k"

[[keys.command]]
key = "prefix+d"
type = "plugin_action"
command = "persiyanov.reviewr.toggle"

[[keys.command]]
key = "ctrl+h"
type = "shell"
command = "exec $HOME/.config/herdr/plugins/github/willfish.herdr-navigator-*/bin/herdr-navigator left ctrl+h"
description = "navigate left"

[[keys.command]]
key = "ctrl+j"
type = "shell"
command = "exec $HOME/.config/herdr/plugins/github/willfish.herdr-navigator-*/bin/herdr-navigator down ctrl+j"
description = "navigate down"

[[keys.command]]
key = "ctrl+k"
type = "shell"
command = "exec $HOME/.config/herdr/plugins/github/willfish.herdr-navigator-*/bin/herdr-navigator up ctrl+k"
description = "navigate up"

[[keys.command]]
key = "ctrl+l"
type = "shell"
command = "exec $HOME/.config/herdr/plugins/github/willfish.herdr-navigator-*/bin/herdr-navigator right ctrl+l"
description = "navigate right"

[ui.sound]
enabled = false
