version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  prettier: &js-prettier
    format-command: 'npx --no prettier --stdin-filepath ${INPUT}'
    format-stdin: true

  rubocop: &ruby-rubocop
    prefix: rubocop
    format-command: 'bundle exec rubocop -A -f quiet --stderr -s ${INPUT}'
    format-stdin: true
    lint-command: 'bundle exec rubocop --format emacs --force-exclusion --stdin ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: W:%m'
    root-markers:
      - .rubocop.yml
      - Gemfile
      - Rakefile

languages:
  javascript:
    - <<: *js-prettier
  javascriptreact:
    - <<: *js-prettier
  ruby:
    - <<: *ruby-rubocop
  typescript:
    - <<: *js-prettier
  typescriptreact:
    - <<: *js-prettier
