[colors.bright]
black = "0x4b505b"
red = "0xd05858"
green = "0x608e32"
yellow = "0xbe7e05"
blue = "0x5079be"
magenta = "0xb05ccc"
cyan = "0x3a8b84"
white = "0xbac3cb"

[colors.normal]
black = "0x8790a0"
red = "0xd05858"
green = "0x608e32"
yellow = "0xbe7e05"
blue = "0x5079be"
magenta = "0xb05ccc"
cyan = "0x3a8b84"
white = "0xdde2e7"

[colors.primary]
background = "0xfafafa"
foreground = "0x4b505b"

[font]
size = 13

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
option_as_alt = "OnlyRight"

[shell]
program = "/bin/zsh"
