[colors.normal]
black ='0x383a42'
red ='0xe45649'
green ='0x50a14f'
yellow ='0xc18401'
blue ='0x0184bc'
magenta ='0xa626a4'
cyan ='0x0997b3'
white ='0xfafafa'

[colors.bright]
black = '0x383a42'
red = '0xe45649'
green = '0x50a14f'
yellow = '0xc18401'
blue = '0x0184bc'
magenta = '0xa626a4'
cyan = '0x0997b3'
white = '0xfafafa'

[colors.primary]
background = '0xfafafa'
foreground = '0x383a42'

[font]
size = 13

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
option_as_alt = "OnlyRight"

[shell]
program = "/bin/zsh"
