[colors.primary]
background = "0xfafafa"
foreground = "0x383a42"

[colors.normal]
black = "0x383a42"
red = "0xe45649"
green = "0x50a14f"
yellow = "0xc18401"
blue = "0x0184bc"
magenta = "0xa626a4"
cyan = "0x0997b3"
white = "0xfafafa"

[colors.bright]
black = "0x383a42"
red = "0xe45649"
green = "0x50a14f"
yellow = "0xc18401"
blue = "0x0184bc"
magenta = "0xa626a4"
cyan = "0x0997b3"
white = "0xfafafa"

[font]
size = 13

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
key = "Tab"
mods = "Control"
chars = "\u001b[9;5u"

# [[keyboard.bindings]]
# chars = "\u001f"
# key = "Slash"
# mods = "Control"

[window]
option_as_alt = "OnlyRight"

[shell]
program = "/bin/zsh"
