[bootstrap.hooks.pre-packages]
run = "./bootstrap/linux/pre-install"

[bootstrap.hooks.post-packages]
run = "./bootstrap/linux/post-install"

[tools]
"aqua:starship/starship" = "latest"

[bootstrap.packages]
"apt:bat" = "latest"
"apt:build-essential" = "latest"
"apt:ca-certificates" = "latest"
"apt:containerd.io" = "latest"
"apt:curl" = "latest"
"apt:docker-ce" = "latest"
"apt:docker-ce-cli" = "latest"
"apt:fish" = "latest"
"apt:fzf" = "latest"
"apt:gh" = "latest"
"apt:git" = "latest"
"apt:inotify-tools" = "latest"
"apt:libffi-dev" = "latest"
"apt:libimage-exiftool-perl" = "latest"
"apt:libreadline-dev" = "latest"
"apt:libssl-dev" = "latest"
"apt:libxml2-dev" = "latest"
"apt:libxslt1-dev" = "latest"
"apt:libyaml-dev" = "latest"
"apt:lsb-release" = "latest"
"apt:make" = "latest"
"apt:neovim" = "latest"
"apt:ntpsec" = "latest"
"apt:pkg-config" = "latest"
"apt:ripgrep" = "latest"
"apt:software-properties-common" = "latest"
"apt:sqlite3" = "latest"
"apt:tig" = "latest"
"apt:unzip" = "latest"
"apt:watchman" = "latest"
"apt:zlib1g-dev" = "latest"

"dnf:bat" = "latest"
"dnf:ca-certificates" = "latest"
"dnf:containerd.io" = "latest"
"dnf:curl" = "latest"
"dnf:docker-ce" = "latest"
"dnf:docker-ce-cli" = "latest"
"dnf:fish" = "latest"
"dnf:fzf" = "latest"
"dnf:gcc" = "latest"
"dnf:gcc-c++" = "latest"
"dnf:gh" = "latest"
"dnf:git" = "latest"
"dnf:inotify-tools" = "latest"
"dnf:libffi-devel" = "latest"
"dnf:libxml2-devel" = "latest"
"dnf:libxslt-devel" = "latest"
"dnf:libyaml-devel" = "latest"
"dnf:make" = "latest"
"dnf:neovim" = "latest"
"dnf:ntpsec" = "latest"
"dnf:openssl-devel" = "latest"
"dnf:perl-Image-ExifTool" = "latest"
"dnf:pkgconf-pkg-config" = "latest"
"dnf:readline-devel" = "latest"
"dnf:ripgrep" = "latest"
"dnf:shellcheck" = "latest"
"dnf:sqlite" = "latest"
"dnf:tig" = "latest"
"dnf:tmux" = "latest"
"dnf:unzip" = "latest"
"dnf:zlib-devel" = "latest"
