[bootstrap.hooks.pre-packages]
run = "./bootstrap/linux/pre-install"

[bootstrap.hooks.post-packages]
run = "./bootstrap/linux/post-install"

[bootstrap.packages]
"apt:bat" = "latest"
"apt:build-essential" = "latest"
"apt:ca-certificates" = "latest"
"apt:containerd.io" = "latest"
"apt:curl" = "latest"
"apt:docker-ce" = "latest"
"apt:docker-ce-cli" = "latest"
"apt:fish" = "latest"
"apt:fzf" = "latest"
"apt:gh" = "latest"
"apt:git" = "latest"
"apt:inotify-tools" = "latest"
"apt:jq" = "latest"
"apt:libffi-dev" = "latest"
"apt:libimage-exiftool-perl" = "latest"
"apt:libreadline-dev" = "latest"
"apt:libssl-dev" = "latest"
"apt:libxml2-dev" = "latest"
"apt:libxslt1-dev" = "latest"
"apt:libyaml-dev" = "latest"
"apt:locales" = "latest"
"apt:lsb-release" = "latest"
"apt:make" = "latest"
"apt:neovim" = "latest"
"apt:ntpsec" = "latest"
"apt:pkg-config" = "latest"
"apt:ripgrep" = "latest"
"apt:software-properties-common" = "latest"
"apt:sqlite3" = "latest"
"apt:starship" = "latest"
"apt:tig" = "latest"
"apt:unzip" = "latest"
"apt:watchman" = "latest"
"apt:zlib1g-dev" = "latest"

