#!/usr/bin/env bash

# Script for managing local PosgtreSQL clusters.
# Usage: `postgres [c]onsole | [u]p | [d]own| [s]tatus {version}`

postgres-console() {
  db=$1
  echo "Postgres - launching psql for ${version}/${db}"
  psql --cluster "$version"/main -U postgres -h localhost -d "$db"
}

postgres-up() {
  echo "Postgres - starting ${version}"
  mkdir -p "$(brew --prefix)/etc/postgresql/14/main/conf.d"
  pg_ctlcluster "${version}" main start
}

postgres-down() {
  echo "Postgres - stopping ${version}"
  pg_ctlcluster "${version}" main stop
}

postgres-status() {
  echo "Postgres - status of ${version}"
  pg_ctlcluster "${version}" main status
}

postgres-help() {
  echo "Usage: postgres [c]onsole | [u]p | [d]own | [s]tatus {version}"
  exit 1
}

command=$1
version=$2

case $command in
  "c" | "console") postgres-console "${3:-postgres}";;
  "u" | "up") postgres-up ;;
  "d" | "down") postgres-down ;;
  "s" | "status") postgres-status ;;
  *) postgres-help ;;
esac
