#!/usr/bin/env bash

# Script for managing local PostgreSQL clusters that allows to run multiple versions in parallel without port conflicts.
# It relies on [postgresql-common](https://github.com/petere/postgresql-common) tool for managing PostgreSQL clusters.
# PostgreSQL is also installed from [peter's formulas](https://github.com/petere/homebrew-postgresql).
#
# Usage: `postgres [c]onsole | [i]nit | [u]p | [d]own | [s]tatus {version}` | setup

# Exit on error
set -e

# Different IPs for PostgreSQL version (127.0.0.10 for 10.x, 127.0.0.11 for 11.x, etc.)
HOSTS=("127.0.0.10" "127.0.0.11" "127.0.0.12" "127.0.0.13" "127.0.0.14" "127.0.0.15" "127.0.0.16" "127.0.0.17")

PLIST_CONTENT=$(cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.user.lo0-IP_ADDRESS.plist</string>
    <key>RunAtLoad</key>
    <true/>
    <key>ProgramArguments</key>
    <array>
      <string>/sbin/ifconfig</string>
      <string>lo0</string>
      <string>alias</string>
      <string>IP_ADDRESS</string>
    </array>
</dict>
</plist>
EOF
)

postgres-setup() {
  echo "Postgres - installing postgresql-common"
  brew tap petere/postgresql
  HOMEBREW_NO_VERIFY_ATTESTATIONS=1 brew install postgresql-common
}

postgres-console() {
  db=${1:-postgres}
  echo "Postgres - launching psql for ${version}/${db}"
  PGHOST=/tmp/${version} psql -d "${db}"
}

postgres-init() {
  echo "Postgres - installing version: ${version}"
  HOMEBREW_NO_VERIFY_ATTESTATIONS=1 brew install -q "petere/postgresql/postgresql@${version}"

  echo "Postgres - creating cluster for version: ${version}"
  local index=$((version - 10))
  local host=${HOSTS[$index]}
  pg_createcluster "${version}" main

  # Reset port to default
  sed -i '' "s/^port = [0-9]\{4\}/port = 5432/" "/opt/homebrew/etc/postgresql/${version}/main/postgresql.conf"
  # Assign lo0 alias as listen address and unix socket directory
  sed -i '' "s/^#listen_addresses = 'localhost'/listen_addresses = '${host}'/" "/opt/homebrew/etc/postgresql/${version}/main/postgresql.conf"
  sed -i '' "s|unix_socket_directories = '/tmp'|unix_socket_directories = '/tmp/${version}'|" "/opt/homebrew/etc/postgresql/${version}/main/postgresql.conf"
  sed -i '' "s/127.0.0.1/${host}/" "/opt/homebrew/etc/postgresql/${version}/main/pg_hba.conf"

  echo "Postgres - creating alias for localhost interface (${host})"
  local file="/Library/LaunchDaemons/com.user.lo0-${host}.plist"

  if [ -f "${file}" ]; then
    sudo launchctl unload "${file}"
    sudo rm "${file}"
  fi

  echo "${PLIST_CONTENT//IP_ADDRESS/${host}}" | sudo tee "${file}" > /dev/null
  sudo chmod 644 "${file}"
  sudo chown root:wheel "${file}"
  sudo launchctl load "${file}"
}

postgres-up() {
  echo "Postgres - starting cluster for version: ${version}"
  mkdir -p "$(brew --prefix)/etc/postgresql/${version}/main/conf.d"
  pg_ctlcluster "${version}" main start
}

postgres-down() {
  echo "Postgres - stopping cluster for version: ${version}"
  pg_ctlcluster "${version}" main stop
}

postgres-remove() {
  echo "Postgres - removing installation: ${version}"
  brew remove "postgresql@${version}"
  echo "Postgres - removing cluster for version: ${version}"
  rm -rf "/opt/homebrew/etc/postgresql/${version}"
}

postgres-status() {
  local index=$((version - 10))
  local host=${HOSTS[$index]}

  echo "Postgres - status of cluster for version: ${version} (${host})"
  pg_ctlcluster "${version}" main status
}

postgres-help() {
  echo "Usage: postgres [c]onsole | [i] init | [u]p | [d]own | [s]tatus {version} | setup"
  exit 1
}

command=$1
version=$2

case $command in
  "c" | "console") postgres-console "${3:-postgres}";;
  "i" | "init") postgres-init ;;
  "u" | "up") postgres-up ;;
  "d" | "down") postgres-down ;;
  "r" | "remove") postgres-remove ;;
  "s" | "status") postgres-status ;;
  "setup") postgres-setup ;;
  *) postgres-help ;;
esac
