suppress_unstable_features_warning = true

[features]
codex_hooks = true

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"
env_http_headers = { "CONTEXT7_API_KEY" = "CONTEXT7_API_KEY" }

[mcp_servers.deepwiki]
url = "https://mcp.deepwiki.com/mcp"

[mcp_servers.deepwiki.tools.ask_question]
approval_mode = "approve"

[mcp_servers.deepwiki.tools.read_wiki_structure]
approval_mode = "approve"

[projects."/Users/lucas/Repos/lcmen/dotfiles"]
trust_level = "trusted"
